[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

board_build.filesystem = littlefs

lib_deps =
  esphome/ESPAsyncWebServer-esphome @ ^3.1.0
  esphome/AsyncTCP-esphome @ ^2.0.3
  bblanchon/ArduinoJson @ ^7

build_flags =
  -DASYNC_TCP_SSL_ENABLED=0
  -DARDUINOJSON_USE_DOUBLE=0
lib_ldf_mode = deep+